language: node_js
node_js:
- '0.10'
git:
  depth: 2147483647
  branch: master
before_script:
- npm install -g grunt-cli
branches:
  only:
  - master
env:
  global:
  - secure: "VDrsPsCpkXsT8lg94LxuICDVpNCPpJGEXFvIwxlzrbtcMR2GT0flaCXLZduQ7+9CB7glStiVWdqLXs+BaC/W4hiUuZo6OYt8PrVBlFoH9Udo6IeTPHP9n1tznUqVl87ErMzBCLlwAnlmoBaMRiWbBZoxHzQHixyvUGZgI0dfPT4="