language: node_js
node_js:
- '0.10'
git:
  depth: 2147483647
  branch: master
before_script:
- npm install -g grunt-cli
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm link npm
- npm install -g bower
- npm link bower
branches:
  only:
  - master
env:
  global:
  - secure: IkxVmLqrbtCl4mhsZ/VJz7mO+vxbYnyqXhbMgaEwdogznav5ltjKFy1cXoeqzBrLkne2h0XbYue+fANlX400BCRc27zkeEdnNzhjCbOrrEIsV7Ikx0a3cXRv4JyUaJ1GQRjADhoxMr+HP2ZM80DWGb6qbcmcJtjap2jhufgwq5g=
  - secure: Log0e83eZ4cIUzfJcUiHVw0P1EXkQepPbN/KMbHyQkgLTvgdWPGSzYJCSuZ7IxuLWymG1SmHssRvUE9PpR0F7qkV6vV8CwA77IBU1WoiStJQpGEvXgLAKCdInbL7JVJd/MS7ZUz+PTmajMsxYtx+7UXFSO9luvLDbLm5KGv0aiA=
