language: node_js
node_js:
- '0.10'
git:
  depth: 2147483647
  branch: master
before_script:
- npm install -g grunt-cli
- npm link npm
branches:
  only:
  - master
env:
  global:
  - secure: "IkxVmLqrbtCl4mhsZ/VJz7mO+vxbYnyqXhbMgaEwdogznav5ltjKFy1cXoeqzBrLkne2h0XbYue+fANlX400BCRc27zkeEdnNzhjCbOrrEIsV7Ikx0a3cXRv4JyUaJ1GQRjADhoxMr+HP2ZM80DWGb6qbcmcJtjap2jhufgwq5g="
  - secure: "b43EPp5cPqigJ1JH1GtcGb/9vNIISaSo+rbA1I+jkJELeSmQduszPF7eh4DdnerSZILM1irNOCrDW4h94fcnk4PE9jk3dLXvncSFU4zznJCvjiCGDUjQ+qLOMocfOfcB6hK1noeenbJ6kpZYgHGY7wWMqQ/r5kz/0ONOQ00zgYg="